spring:
  main:
    banner-mode: off
  docker:
    compose:
      enabled: false
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
logging:
  level:
    root: warn
    io.github.pgatzka.taskmaster: info