[versions]
mapstruct = "1.6.3"

[libraries]
org-flywaydb_flyway-database-postgresql = { group = "org.flywaydb", name = "flyway-database-postgresql" }
org-hibernate-orm_hibernate-processor = { group = "org.hibernate.orm", name = "hibernate-processor" }
org-junit-platform_junit-platform-launcher = { group = "org.junit.platform", name = "junit-platform-launcher" }
org-mapstruct_mapstruct = { group = "org.mapstruct", name = "mapstruct", version.ref = "mapstruct" }
org-mapstruct_mapstruct-processor = { group = "org.mapstruct", name = "mapstruct-processor", version.ref = "mapstruct" }
org-postgresql_postgresql = { group = "org.postgresql", name = "postgresql" }
org-projectlombok_lombok = { group = "org.projectlombok", name = "lombok" }
org-projectlombok_lombok-mapstruct-binding = { group = "org.projectlombok", name = "lombok-mapstruct-binding", version = "0.2.0" }
org-springframework-boot_spring-boot-docker-compose = { group = "org.springframework.boot", name = "spring-boot-devtools" }
org-springframework-boot_spring-boot-devtools = { group = "org.springframework.boot", name = "spring-boot-docker-compose" }
org-springframework-boot_spring-boot-starter-data-jpa = { group = "org.springframework.boot", name = "spring-boot-starter-data-jpa" }
org-springframework-boot_spring-boot-starter-data-jpa-test = { group = "org.springframework.boot", name = "spring-boot-starter-data-jpa-test" }
org-springframework-boot_spring-boot-starter-flyway = { group = "org.springframework.boot", name = "spring-boot-starter-flyway" }
org-springframework-boot_spring-boot-starter-flyway-test = { group = "org.springframework.boot", name = "spring-boot-starter-flyway-test" }
org-springframework-boot_spring-boot-starter-validation = { group = "org.springframework.boot", name = "spring-boot-starter-validation" }
org-springframework-boot_spring-boot-starter-validation-test = { group = "org.springframework.boot", name = "spring-boot-starter-validation-test" }
org-springframework-boot_spring-boot-starter-webmvc = { group = "org.springframework.boot", name = "spring-boot-starter-webmvc" }
org-springframework-boot_spring-boot-starter-webmvc-test = { group = "org.springframework.boot", name = "spring-boot-starter-webmvc-test" }
org-springframework-boot_spring-boot-testcontainers = { group = "org.springframework.boot", name = "spring-boot-testcontainers" }
org-testcontainers_testcontainers-junit-jupiter = { group = "org.testcontainers", name = "testcontainers-junit-jupiter" }
org-testcontainers_testcontainers-postgresql = { group = "org.testcontainers", name = "testcontainers-postgresql" }

[bundles]
annotationProcessor = ["org-hibernate-orm_hibernate-processor", "org-mapstruct_mapstruct-processor", "org-projectlombok_lombok", "org-projectlombok_lombok-mapstruct-binding"]
compileOnly = ["org-projectlombok_lombok"]
developmentOnly = ["org-springframework-boot_spring-boot-devtools", "org-springframework-boot_spring-boot-docker-compose"]
implementation = ["org-flywaydb_flyway-database-postgresql", "org-mapstruct_mapstruct", "org-springframework-boot_spring-boot-starter-data-jpa", "org-springframework-boot_spring-boot-starter-flyway", "org-springframework-boot_spring-boot-starter-validation", "org-springframework-boot_spring-boot-starter-webmvc"]
runtimeOnly = ["org-postgresql_postgresql"]
testAnnotationProcessor = ["org-projectlombok_lombok"]
testCompileOnly = ["org-projectlombok_lombok"]
testImplementation = ["org-springframework-boot_spring-boot-starter-data-jpa-test", "org-springframework-boot_spring-boot-starter-flyway-test", "org-springframework-boot_spring-boot-starter-validation-test", "org-springframework-boot_spring-boot-starter-webmvc-test", "org-springframework-boot_spring-boot-testcontainers", "org-testcontainers_testcontainers-postgresql", "org-testcontainers_testcontainers-junit-jupiter"]
testRuntimeOnly = ["org-junit-platform_junit-platform-launcher"]

[plugins]
io-spring-dependency-management = { id = "io.spring.dependency-management", version = "1.1.7" }
org-springframework-boot = { id = "org.springframework.boot", version = "4.1.1" }
