/*
 * This source file was generated by the Gradle 'init' task
 */
package io.github.pgatzka.taskmaster;

public class Application {

    static void main(String[] args) {
        System.out.println("Hello World!");
    }

}
